/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.genius.view.admin;

import edu.ijse.gdse37.genius.connector.ServerConnector;
import edu.ijse.gdse37.genius.view.other.ComboSearch;
import edu.ijse.gdse37.genius_common.controllers.StudentController;
import edu.ijse.gdse37.genius_common.model.Student;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinuka
 */
public class CompareStudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompareStudentPanel
     */
    public CompareStudentPanel() {
        initComponents();
        loadStudentList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWindowPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        windowPanel = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        student_idCOmbo = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();
        nameTxt = new javax.swing.JLabel();

        mainWindowPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainWindowPanel.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/genius/view/images/logo2New.png"))); // NOI18N
        mainWindowPanel.add(jLabel1);
        jLabel1.setBounds(950, 550, 190, 90);

        windowPanel.setLayout(new java.awt.BorderLayout());

        imagePanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/genius/view/images/LOGO.png"))); // NOI18N

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        windowPanel.add(imagePanel, java.awt.BorderLayout.CENTER);

        mainWindowPanel.add(windowPanel);
        windowPanel.setBounds(40, 30, 1070, 500);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Show Chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainWindowPanel.add(jButton1);
        jButton1.setBounds(43, 560, 220, 40);

        student_idCOmbo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mainWindowPanel.add(student_idCOmbo);
        student_idCOmbo.setBounds(600, 550, 240, 30);

        searchBtn.setBackground(new java.awt.Color(255, 255, 255));
        searchBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        mainWindowPanel.add(searchBtn);
        searchBtn.setBounds(850, 550, 90, 30);

        nameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainWindowPanel.add(nameTxt);
        nameTxt.setBounds(600, 590, 240, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainWindowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWindowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imagePanel.setVisible(false);
        SetFXMLToJava.setFXMLToPanel(windowPanel);
        windowPanel.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            StudentController studentController = ServerConnector.getServerConnector().getStudentController();
            if (student_idCOmbo.getSelectedItem() != null) {
                Student student = studentController.searchStudent("student_id", student_idCOmbo.getSelectedItem().toString());
                if (student != null) {
                    nameTxt.setText(student.getName());
                } else {
                    JOptionPane.showMessageDialog(this, "Somthing wrong..student combo");
                }
            } else {
                //Do nothing...
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(CompareStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(CompareStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CompareStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CompareStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainWindowPanel;
    private javax.swing.JLabel nameTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> student_idCOmbo;
    private javax.swing.JPanel windowPanel;
    // End of variables declaration//GEN-END:variables

    /*Method for load student Id to combo © Dinuka Kasun Medis*/
    private void loadStudentList() {
        try {
            student_idCOmbo.removeAllItems();
            StudentController studentController = ServerConnector.getServerConnector().getStudentController();
            ArrayList<Student> studentList = studentController.getAllStudent();
            if (studentList != null) {
                for (Student student : studentList) {
                    student_idCOmbo.addItem(student.getStudent_id());
                }
            }
            new ComboSearch().setSearchableCombo(student_idCOmbo, true, "No Student found");
        } catch (NotBoundException ex) {
            Logger.getLogger(CompareStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(CompareStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CompareStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CompareStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
