/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.genius.view.admin;

/**
 *
 * @author Dinuka
 */
public class ExamPanel extends javax.swing.JPanel {

    private final Admin_Main_Window ADMIN_MAIN_WINDOW;
    private final AutomaticallyExamCreate AUTOMATICALLY_EXAM_CREATE;
    private final ManualExamCreate MANUAL_EXAM_CREATE;
    private final SelectExamPanel SELECT_EXAM_PANEL;
    /**
     * Creates new form ExamPanel
     * @param admin_Main_Window
     */
    public ExamPanel(Admin_Main_Window admin_Main_Window) {
        initComponents();
        this.ADMIN_MAIN_WINDOW=admin_Main_Window;
        AUTOMATICALLY_EXAM_CREATE=new AutomaticallyExamCreate(admin_Main_Window);
        MANUAL_EXAM_CREATE=new ManualExamCreate(admin_Main_Window);
        SELECT_EXAM_PANEL=new SelectExamPanel(admin_Main_Window);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        automatBtn = new javax.swing.JButton();
        manualBtn = new javax.swing.JButton();

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/genius/view/images/logo2New.png"))); // NOI18N
        backPanel.add(jLabel8);
        jLabel8.setBounds(950, 550, 190, 90);

        viewBtn.setBackground(new java.awt.Color(179, 240, 244));
        viewBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        viewBtn.setText("Select Exam");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        backPanel.add(viewBtn);
        viewBtn.setBounds(210, 320, 720, 60);

        automatBtn.setBackground(new java.awt.Color(179, 240, 244));
        automatBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        automatBtn.setText("Create New Exam Automatically");
        automatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automatBtnActionPerformed(evt);
            }
        });
        backPanel.add(automatBtn);
        automatBtn.setBounds(210, 120, 720, 60);

        manualBtn.setBackground(new java.awt.Color(179, 240, 244));
        manualBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        manualBtn.setText("Create New Exam Manually");
        manualBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualBtnActionPerformed(evt);
            }
        });
        backPanel.add(manualBtn);
        manualBtn.setBounds(210, 220, 720, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        Admin_Main_Window.mainWindowPanel.removeAll();
        Admin_Main_Window.mainWindowPanel.add(SELECT_EXAM_PANEL);
        Admin_Main_Window.mainWindowPanel.repaint();
        Admin_Main_Window.mainWindowPanel.revalidate();
        SELECT_EXAM_PANEL.setVisible(true);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void manualBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualBtnActionPerformed
        Admin_Main_Window.mainWindowPanel.removeAll();
        Admin_Main_Window.mainWindowPanel.add(MANUAL_EXAM_CREATE);
        Admin_Main_Window.mainWindowPanel.repaint();
        Admin_Main_Window.mainWindowPanel.revalidate();
        MANUAL_EXAM_CREATE.setVisible(true);
    }//GEN-LAST:event_manualBtnActionPerformed

    private void automatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automatBtnActionPerformed
        Admin_Main_Window.mainWindowPanel.removeAll();
        Admin_Main_Window.mainWindowPanel.add(AUTOMATICALLY_EXAM_CREATE);
        Admin_Main_Window.mainWindowPanel.repaint();
        Admin_Main_Window.mainWindowPanel.revalidate();
        AUTOMATICALLY_EXAM_CREATE.setVisible(true);
    }//GEN-LAST:event_automatBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton automatBtn;
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton manualBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
