/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.genius.view.admin;

import edu.ijse.gdse37.genius.connector.ServerConnector;
import edu.ijse.gdse37.genius.observerImpl.AdminObserverImpl;
import edu.ijse.gdse37.genius.view.other.ComboSearch;
import edu.ijse.gdse37.genius.view.other.Encription;
import edu.ijse.gdse37.genius.view.other.Validation;
import edu.ijse.gdse37.genius_common.controllers.AdminController;
import edu.ijse.gdse37.genius_common.controllers.IDController;
import edu.ijse.gdse37.genius_common.controllers.StudentController;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import edu.ijse.gdse37.genius_common.model.Student;
import java.awt.Color;
import java.io.UnsupportedEncodingException;

/**
 *
 * @author Dinuka
 */
public class ManageStudentPanel extends javax.swing.JPanel {

    private final Admin_Main_Window admin_Main_Window;
    private ViewStudentList VIEW_STUDENT_LIST;
    private SpecialLogin specialLogin;
    private AdminObserverImpl adminObserverImpl;

    /**
     * Creates new form ManageStudentPanel
     *
     * @param admin_Main_Window
     */
    public ManageStudentPanel(Admin_Main_Window admin_Main_Window) {
        this.admin_Main_Window = admin_Main_Window;
        initComponents();
        loadStudentList();
        student_idTxt.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWindowPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nicTxt = new javax.swing.JTextField();
        student_idCOmbo = new javax.swing.JComboBox<>();
        student_idTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        telephoneTxt = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        passwordTxt = new javax.swing.JTextField();
        newStudentBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        VisibleTrue = new javax.swing.JLabel();
        VisibleFalse = new javax.swing.JLabel();

        mainWindowPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainWindowPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("NIC :");
        mainWindowPanel.add(jLabel1);
        jLabel1.setBounds(170, 370, 100, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Student Id :");
        mainWindowPanel.add(jLabel2);
        jLabel2.setBounds(170, 120, 100, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Name :");
        mainWindowPanel.add(jLabel3);
        jLabel3.setBounds(170, 170, 100, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Email :");
        mainWindowPanel.add(jLabel4);
        jLabel4.setBounds(170, 220, 100, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Telephone :");
        mainWindowPanel.add(jLabel5);
        jLabel5.setBounds(170, 270, 100, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Password :");
        mainWindowPanel.add(jLabel6);
        jLabel6.setBounds(170, 320, 100, 30);

        nicTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nicTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicTxtKeyReleased(evt);
            }
        });
        mainWindowPanel.add(nicTxt);
        nicTxt.setBounds(280, 370, 270, 30);

        student_idCOmbo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        student_idCOmbo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                student_idCOmboItemStateChanged(evt);
            }
        });
        mainWindowPanel.add(student_idCOmbo);
        student_idCOmbo.setBounds(280, 120, 240, 30);

        student_idTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        student_idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_idTxtActionPerformed(evt);
            }
        });
        mainWindowPanel.add(student_idTxt);
        student_idTxt.setBounds(280, 120, 240, 30);

        nameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTxtKeyReleased(evt);
            }
        });
        mainWindowPanel.add(nameTxt);
        nameTxt.setBounds(280, 170, 410, 30);

        emailTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mainWindowPanel.add(emailTxt);
        emailTxt.setBounds(280, 220, 360, 30);

        telephoneTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        telephoneTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telephoneTxtKeyReleased(evt);
            }
        });
        mainWindowPanel.add(telephoneTxt);
        telephoneTxt.setBounds(280, 270, 270, 30);

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });
        mainWindowPanel.add(passwordField);
        passwordField.setBounds(280, 320, 270, 30);

        passwordTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mainWindowPanel.add(passwordTxt);
        passwordTxt.setBounds(280, 320, 270, 30);

        newStudentBtn.setBackground(new java.awt.Color(255, 255, 255));
        newStudentBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newStudentBtn.setText("New Sudent");
        newStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentBtnActionPerformed(evt);
            }
        });
        mainWindowPanel.add(newStudentBtn);
        newStudentBtn.setBounds(160, 520, 150, 50);

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        mainWindowPanel.add(addBtn);
        addBtn.setBounds(160, 520, 150, 50);

        updateBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        mainWindowPanel.add(updateBtn);
        updateBtn.setBounds(330, 520, 150, 50);

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        mainWindowPanel.add(deleteBtn);
        deleteBtn.setBounds(500, 520, 150, 50);

        viewBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        viewBtn.setText(" View All");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        mainWindowPanel.add(viewBtn);
        viewBtn.setBounds(670, 520, 150, 50);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/genius/view/images/logo2New.png"))); // NOI18N
        mainWindowPanel.add(jLabel7);
        jLabel7.setBounds(950, 550, 190, 90);

        VisibleTrue.setBackground(new java.awt.Color(210, 205, 205));
        VisibleTrue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/genius/view/images/eye.png"))); // NOI18N
        VisibleTrue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisibleTrueMouseClicked(evt);
            }
        });
        mainWindowPanel.add(VisibleTrue);
        VisibleTrue.setBounds(550, 320, 20, 30);

        VisibleFalse.setBackground(new java.awt.Color(210, 205, 205));
        VisibleFalse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/genius/view/images/eye.png"))); // NOI18N
        VisibleFalse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisibleFalseMouseClicked(evt);
            }
        });
        mainWindowPanel.add(VisibleFalse);
        VisibleFalse.setBounds(550, 320, 20, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainWindowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWindowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void student_idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_idTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            StudentController studentController = ServerConnector.getServerConnector().getStudentController();
            String student_id = student_idTxt.getText();
            String name = nameTxt.getText();
            String email = emailTxt.getText();
            int telephone = Integer.parseInt(telephoneTxt.getText());
            String password = Encription.encriptTxt(passwordTxt.getText());//encript(passwordTxt.getText());
            String nic = nicTxt.getText();
            Student student = new Student(student_id, name, nic, email, telephone, password);
            boolean isAdded = studentController.isAddStudent(student);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Student added sucsess...");
                student_idTxt.setVisible(false);
                newStudentBtn.setVisible(true);
                student_idCOmbo.setVisible(true);
                loadStudentList();
            } else {
                JOptionPane.showMessageDialog(this, "Somthing wrong...student add");
                newStudentBtn.setVisible(true);
                student_idCOmbo.setVisible(true);
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            specialLogin = new SpecialLogin(admin_Main_Window, true);
            specialLogin.setVisible(true);
            StudentController studentController = ServerConnector.getServerConnector().getStudentController();
            String student_id = student_idCOmbo.getSelectedItem().toString();
            String name = nameTxt.getText();
            String email = emailTxt.getText();
            int telephone = Integer.parseInt(telephoneTxt.getText());
            String password = Encription.encriptTxt(passwordTxt.getText());
            String nic = nicTxt.getText();
            Student student = new Student(student_id, name, nic, email, telephone, password);
            boolean isUpdated = studentController.isUpdateStudent(student);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Student updated sucsess...");
                setTxtFree();
                loadStudentList();
            } else {
                JOptionPane.showMessageDialog(this, "Somthing wrong...student update");
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try {
            specialLogin = new SpecialLogin(admin_Main_Window, true);
            specialLogin.setVisible(true);
            StudentController studentController = ServerConnector.getServerConnector().getStudentController();
            String student_id = student_idCOmbo.getSelectedItem().toString();
            boolean isDeleted = studentController.isDeleteStudent(student_id);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Student deleted sucsess...");
                setTxtFree();
                loadStudentList();
            } else {
                JOptionPane.showMessageDialog(this, "Somthing wrong...student delete");
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        Admin_Main_Window.setBtnDissable();
        addAdminObserver();
        VIEW_STUDENT_LIST = new ViewStudentList(this.admin_Main_Window);
        Admin_Main_Window.mainWindowPanel.removeAll();
        Admin_Main_Window.mainWindowPanel.add(VIEW_STUDENT_LIST);
        Admin_Main_Window.mainWindowPanel.repaint();
        Admin_Main_Window.mainWindowPanel.revalidate();
        VIEW_STUDENT_LIST.setVisible(true);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void student_idCOmboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_student_idCOmboItemStateChanged
        try {
            StudentController studentController = ServerConnector.getServerConnector().getStudentController();
            if (student_idCOmbo.getSelectedItem() != null) {
                Student student = studentController.searchStudent("student_id", student_idCOmbo.getSelectedItem().toString());
                if (student != null) {
                    nameTxt.setText(student.getName());
                    emailTxt.setText(student.getEmail());
                    nicTxt.setText(student.getNic());
                    telephoneTxt.setText(Integer.toString(student.getTel()));
                    passwordTxt.setText(Encription.decriptTxt(student.getPassword()));
                    passwordField.setText(Encription.decriptTxt(student.getPassword()));
                } else {
                    JOptionPane.showMessageDialog(this, "Somthing wrong..student combo");
                }
            } else {
                //Do nothing..
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_student_idCOmboItemStateChanged

    private void newStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentBtnActionPerformed
        try {
            student_idCOmbo.setVisible(false);
            newStudentBtn.setVisible(false);
            student_idTxt.setVisible(true);
            setTxtFree();
            IDController iDController = ServerConnector.getServerConnector().getIDController();
            String newId = iDController.getLastId("Student");
            student_idTxt.setText(newId);
        } catch (NotBoundException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newStudentBtnActionPerformed

    private void telephoneTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneTxtKeyReleased
        Validation.phoneNumber(telephoneTxt);
    }//GEN-LAST:event_telephoneTxtKeyReleased

    private void nicTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTxtKeyReleased
        boolean isCorrect = Validation.validateNic(nicTxt.getText());
        if (!isCorrect) {
            nicTxt.setForeground(Color.red);
        } else {
            nicTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_nicTxtKeyReleased

    private void nameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyReleased
//        boolean isCorrect = Validation.validateTxt(nameTxt.getText());
//        if (!isCorrect) {
//            nameTxt.setForeground(Color.red);
//        } else {
//            nameTxt.setForeground(Color.black);
//        }
    }//GEN-LAST:event_nameTxtKeyReleased

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
       passwordTxt.setText(passwordConverter());
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void VisibleFalseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisibleFalseMouseClicked
        VisibleFalse.setVisible(false);
        passwordTxt.setVisible(false);
        passwordField.setVisible(true);
        VisibleTrue.setVisible(true);
    }//GEN-LAST:event_VisibleFalseMouseClicked

    private void VisibleTrueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisibleTrueMouseClicked
        VisibleTrue.setVisible(false);
        passwordTxt.setVisible(true);
        passwordField.setVisible(false);
        VisibleFalse.setVisible(true);
    }//GEN-LAST:event_VisibleTrueMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VisibleFalse;
    private javax.swing.JLabel VisibleTrue;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel mainWindowPanel;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton newStudentBtn;
    private javax.swing.JTextField nicTxt;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JComboBox<String> student_idCOmbo;
    private javax.swing.JTextField student_idTxt;
    private javax.swing.JTextField telephoneTxt;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

    /*Method for load student id to combo © Dinuka Kasun Medis*/
    private void loadStudentList() {
        try {
            student_idCOmbo.removeAllItems();
            StudentController studentController = ServerConnector.getServerConnector().getStudentController();
            ArrayList<Student> studentList = studentController.getAllStudent();
            if (studentList != null) {
                for (Student student : studentList) {
                    student_idCOmbo.addItem(student.getStudent_id());
                }
            }
            new ComboSearch().setSearchableCombo(student_idCOmbo, true, "No Student found");
        } catch (NotBoundException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addAdminObserver() {
        try {
            AdminController adminController = ServerConnector.getServerConnector().getAdminController();
            adminObserverImpl = new AdminObserverImpl(admin_Main_Window);
            adminController.isAddAdminObserver(adminObserverImpl);
        } catch (NotBoundException ex) {
            Logger.getLogger(ViewAdminList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ViewAdminList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ViewAdminList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ViewAdminList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*Method for free all txt fields © Dinuka Kasun Medis*/
    private void setTxtFree() {
        nameTxt.setText("");
        emailTxt.setText("");
        telephoneTxt.setText("");
        passwordTxt.setText("");
        nicTxt.setText("");
    }

    /*Method for password to text © Dinuka Kasun Medis*/
    private String passwordConverter() {
        String passwordData = null;
        try {
            char[] password = passwordField.getPassword();
            String s = new String(password);
            byte[] password2 = s.getBytes("UTF-8");
            passwordData = new String(password2);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return passwordData;
    }
}
