/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.genius.view.admin;

/**
 *
 * @author Dinuka
 */
public class QuestionPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form QuestionPanel2
     */
    public QuestionPanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        qNoLbl = new javax.swing.JLabel();
        chekBox1 = new javax.swing.JCheckBox();
        chekBox2 = new javax.swing.JCheckBox();
        chekBox3 = new javax.swing.JCheckBox();
        chekBox4 = new javax.swing.JCheckBox();
        chekBox5 = new javax.swing.JCheckBox();

        jPanel1.setLayout(null);

        qNoLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        qNoLbl.setText("1 .)");
        jPanel1.add(qNoLbl);
        qNoLbl.setBounds(10, 10, 34, 20);
        jPanel1.add(chekBox1);
        chekBox1.setBounds(50, 10, 20, 21);
        jPanel1.add(chekBox2);
        chekBox2.setBounds(80, 10, 20, 21);
        jPanel1.add(chekBox3);
        chekBox3.setBounds(110, 10, 20, 21);
        jPanel1.add(chekBox4);
        chekBox4.setBounds(140, 10, 20, 21);
        jPanel1.add(chekBox5);
        chekBox5.setBounds(170, 10, 20, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox chekBox1;
    public javax.swing.JCheckBox chekBox2;
    public javax.swing.JCheckBox chekBox3;
    public javax.swing.JCheckBox chekBox4;
    public javax.swing.JCheckBox chekBox5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel qNoLbl;
    // End of variables declaration//GEN-END:variables
}
