/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.genius.view.admin;

import edu.ijse.gdse37.genius.connector.ServerConnector;
import edu.ijse.gdse37.genius_common.controllers.ExamController;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import edu.ijse.gdse37.genius_common.model.Exam;

/**
 *
 * @author Dinuka
 */
public class SelectExamPanel extends javax.swing.JPanel {

    private ExamPaperPriviewPanel examPaperPriviewPanel;
    private final Admin_Main_Window admin_Main_Window;
    /**
     * Creates new form SelectExamPanel
     * @param admin_Main_Window
     */
    public SelectExamPanel(Admin_Main_Window admin_Main_Window) {
        initComponents();
        this.admin_Main_Window=admin_Main_Window;
        getAllExams();
        selectExamTable.setRowHeight(30);
        selectExamTable.getTableHeader().setFont(new Font("Times New Roman", Font.PLAIN, 18));
        selectExamTable.getTableHeader().setBackground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectExamTable = new javax.swing.JTable();
        viewBtn = new javax.swing.JButton();

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/genius/view/images/logo2New.png"))); // NOI18N
        backPanel.add(jLabel8);
        jLabel8.setBounds(950, 550, 190, 90);

        selectExamTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        selectExamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam Id", "Exam Name", "Subject", "Unite", "No of Questions"
            }
        ));
        jScrollPane1.setViewportView(selectExamTable);
        if (selectExamTable.getColumnModel().getColumnCount() > 0) {
            selectExamTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            selectExamTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            selectExamTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            selectExamTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            selectExamTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        backPanel.add(jScrollPane1);
        jScrollPane1.setBounds(50, 60, 1040, 490);

        viewBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        viewBtn.setText("Preview");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        backPanel.add(viewBtn);
        viewBtn.setBounds(50, 560, 230, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        int rowNo=selectExamTable.getSelectedRow();
        if (selectExamTable.getSelectedRow()>=0) {
            String exam_id=selectExamTable.getValueAt(rowNo, 0).toString();
            String examName=selectExamTable.getValueAt(rowNo, 1).toString();
            String subject=selectExamTable.getValueAt(rowNo, 2).toString();
            String unite=selectExamTable.getValueAt(rowNo, 3).toString();
            int numberOfQuestions=Integer.parseInt(selectExamTable.getValueAt(rowNo, 4).toString());
            examPaperPriviewPanel=new ExamPaperPriviewPanel(exam_id,examName,subject,unite,numberOfQuestions,admin_Main_Window);
            Admin_Main_Window.mainWindowPanel.removeAll();
            Admin_Main_Window.mainWindowPanel.add(examPaperPriviewPanel);
            Admin_Main_Window.mainWindowPanel.repaint();
            Admin_Main_Window.mainWindowPanel.revalidate();
            examPaperPriviewPanel.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Please select an exam!");
        }
        
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable selectExamTable;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

    /*Method for add load all exams to table © Dinuka Kasun Medis*/
    private void getAllExams(){
        try {
            ExamController examController=ServerConnector.getServerConnector().getExamController();
            ArrayList<Exam> examList=examController.getAllExam();
            DefaultTableModel dtm=(DefaultTableModel) selectExamTable.getModel();
            dtm.setRowCount(0);
            if (examList!=null) {
                for (Exam exam : examList) {
                    Object []raw={exam.getExam_id(),exam.getExam_name(),exam.getSubject(),exam.getUnite(),exam.getNo_of_questions()};
                    dtm.addRow(raw);
                }
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(SelectExamPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SelectExamPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(SelectExamPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SelectExamPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
